FROM node:24 AS builder
WORKDIR /juice-shop
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts
COPY . .
RUN npx tsc

FROM bkimminich/juice-shop:latest
COPY --from=builder /juice-shop/build /juice-shop/build
